### ISSUE TITLE
Support light mode

### ISSUE THREAD

**Issue by dvadas** [JustinGrote/azure-xray#4]
The UI is currently unreadable when using light mode.

This was in Edge on Windows.

**Comment by JustinGrote** [comment]
Thanks for your submission! Yep this is first on the docket for next release, the devtools theming is very difficult and has to be done manually for the most part, so I wanted to at least get dark right for the MVP.

**Comment by JustinGrote** [comment]
Fixed in https://github.com/JustinGrote/azure-xray/commit/89721370e5df7ebfe4450889ccc702354697bb5e, 0.0.2 will be out as soon as MS approves it, 3-7 business days.
